name: Continuous Integration
on:
  pull_request:
    branches: main
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3.1.0
      - name: Lint
        uses: github/super-linter@v4.9.7